#server:
#  port: 8080
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_test
    username: root
    password: 1234



mybatis:
  type-aliases-package: com.dalicious.dalicious.domain
  mapper-locations: mappers/*.xml